// TODO MY ORDER PAGE

// TODO cross-origin-opener problem when signInWithGoogle.... 

// TODO WHEN HOVER NAVCART CHANGE NUMBER AND WHEN HOVER NUMBER CHANGE NAVCART COLOR

// TODO ADD NOPRODUCT COMPONENT TO THE ORDERS ACCOUNT IF EMPTY

// TODO WHEN I SEE PRODUCT STORAGE --> COOKIE SAMESITE PROBLEM

// TODO NEED TO PUT AUTOCOMPLETE ATTRIBUTE ON SIGN IN PAGE