// TODO THE MULTIPLE PAGE ON MEDIAQUERY

// TODO HAVING USER AUTHENTIFICATION AND CONNECT ON FIREBASE

// TODO USER NAVICON NEED TO SEND TO THE SIGN PAGE WHEN NO USER IS CONNECT

// TODO MAKE THE FONT WORK ON ANDROID
